typography_spectrum: 0.92922138934955
color:
  brandStrength: 0.750229744007811
  lightness: 0.882371915737167
  saturation: 0.3374070846475661
  rhythmicContrast: 0.6070147620048374
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
github: true
layout_spectrum: 0.048022639006376266
name: configuration science
title: Configuration Science Ltd
content: []
description: identity and access management for multi-disciplinary care communication
