layout_spectrum: 0.042257778629715935
typography_spectrum: 0.5363762506908083
color:
  brandStrength: 0.41969387451647827
  lightness: 0.931930272006107
  saturation: 0.13247882527188573
  rhythmicContrast: 0.8502186272228782
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
github: true
author:
  name: Adam Saltiel
  email: adam.saltiel@gmail.com
  url: 'http://configurationscience.co.uk'
name: configuration science
title: Configuration Science Ltd
content: []
description: identity and access management for multi-disciplinary care communication
