layout_spectrum: 0.046298742346963524
typography_spectrum: 0.3110539740669808
color:
  brandStrength: 0.27648144168760813
  lightness: 0.8289091079789075
  saturation: 0.8255365630605322
  rhythmicContrast: 0.38536118970151145
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
github: true
author:
  name: Adam Saltiel
  email: adam.saltiel@gmail.com
  url: 'http://configurationscience.co.uk'
name: configuration science
title: Configuration Science Ltd
content: []
description: identity and access management for multi-disciplinary care communication
